name: SimpleWorldManager
version: 0.0.45
main: com.aglareb.simpleworldmanager.SimpleWorldManager
description: A simple system for adding and deleting worlds
author: aglareb
website: https://aglareb.com/SimpleWorldManager.html
api-version: 1.20
load: STARTUP
